apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: segundodesafio
type: Opaque
stringData:
  POSTGRES_PASSWORD: "CHANGE_ME_ADMIN"
  AUTHENTICATOR_PASSWORD: "CHANGE_ME_API"
  uri: "postgres://authenticator:CHANGE_ME_API@postgres-service:5432/appdb"