apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: segundodesafio
type: Opaque
stringData:
  POSTGRES_PASSWORD: "CHANGE_ME"
  uri: "postgres://appuser:CHANGE_ME@postgres-service:5432/appdb"